services:
  - type: web
    name: microwin-app
    env: docker
    plan: free
    healthCheckPath: /api/v1/tasks/health
    dockerfilePath: ./Dockerfile
    dockerContext: .
    buildArgs:
      VITE_GOOGLE_CLIENT_ID: "7121665160-qe51dk6m1nf2o39u830q5303d4ehthj0.apps.googleusercontent.com"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: microwin-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: DB_ENCRYPTION_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        value: "7121665160-qe51dk6m1nf2o39u830q5303d4ehthj0.apps.googleusercontent.com"
      - key: FRONTEND_URL
        value: "https://microwin.onrender.com"

databases:
  - name: microwin-db
    databaseName: microwin
    user: microwin
    plan: free
